language: php
  ​
cache:
  directories:
    - $HOME/.composer/cache
  ​
php:
  - 7.2
  - 7.3
  - 7.4
  ​
matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION=4.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*
    - php: 7.2
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*
  ​
before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  ​
script:
  - ./vendor/bin/grumphp run
